// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf-define.proto
package org.example;

public final class PB {
  private PB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bool is_valid = 1;
    /**
     * <code>optional bool is_valid = 1;</code>
     */
    boolean hasIsValid();
    /**
     * <code>optional bool is_valid = 1;</code>
     */
    boolean getIsValid();

    // optional int64 expand_bit = 2;
    /**
     * <code>optional int64 expand_bit = 2;</code>
     */
    boolean hasExpandBit();
    /**
     * <code>optional int64 expand_bit = 2;</code>
     */
    long getExpandBit();

    // optional string title = 3;
    /**
     * <code>optional string title = 3;</code>
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 3;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 3;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    // optional int32 channel_id = 4;
    /**
     * <code>optional int32 channel_id = 4;</code>
     */
    boolean hasChannelId();
    /**
     * <code>optional int32 channel_id = 4;</code>
     */
    int getChannelId();

    // repeated string virtual_channel = 12;
    /**
     * <code>repeated string virtual_channel = 12;</code>
     */
    java.util.List<java.lang.String>
    getVirtualChannelList();
    /**
     * <code>repeated string virtual_channel = 12;</code>
     */
    int getVirtualChannelCount();
    /**
     * <code>repeated string virtual_channel = 12;</code>
     */
    java.lang.String getVirtualChannel(int index);
    /**
     * <code>repeated string virtual_channel = 12;</code>
     */
    com.google.protobuf.ByteString
        getVirtualChannelBytes(int index);

    // optional double sns_score = 13;
    /**
     * <code>optional double sns_score = 13;</code>
     */
    boolean hasSnsScore();
    /**
     * <code>optional double sns_score = 13;</code>
     */
    double getSnsScore();

    // repeated int64 child_clip_id = 111;
    /**
     * <code>repeated int64 child_clip_id = 111;</code>
     */
    java.util.List<java.lang.Long> getChildClipIdList();
    /**
     * <code>repeated int64 child_clip_id = 111;</code>
     */
    int getChildClipIdCount();
    /**
     * <code>repeated int64 child_clip_id = 111;</code>
     */
    long getChildClipId(int index);
  }
  /**
   * Protobuf type {@code Info}
   */
  public static final class Info extends
      com.google.protobuf.GeneratedMessage
      implements InfoOrBuilder {
    // Use Info.newBuilder() to construct.
    private Info(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Info(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Info defaultInstance;
    public static Info getDefaultInstance() {
      return defaultInstance;
    }

    public Info getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Info(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isValid_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              expandBit_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              title_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              channelId_ = input.readInt32();
              break;
            }
            case 98: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                virtualChannel_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              virtualChannel_.add(input.readBytes());
              break;
            }
            case 105: {
              bitField0_ |= 0x00000010;
              snsScore_ = input.readDouble();
              break;
            }
            case 888: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                childClipId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000040;
              }
              childClipId_.add(input.readInt64());
              break;
            }
            case 890: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040) && input.getBytesUntilLimit() > 0) {
                childClipId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000040;
              }
              while (input.getBytesUntilLimit() > 0) {
                childClipId_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          virtualChannel_ = new com.google.protobuf.UnmodifiableLazyStringList(virtualChannel_);
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          childClipId_ = java.util.Collections.unmodifiableList(childClipId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PB.internal_static_Info_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PB.internal_static_Info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PB.Info.class, PB.Info.Builder.class);
    }

    public static com.google.protobuf.Parser<Info> PARSER =
        new com.google.protobuf.AbstractParser<Info>() {
      public Info parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Info(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Info> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bool is_valid = 1;
    public static final int IS_VALID_FIELD_NUMBER = 1;
    private boolean isValid_;
    /**
     * <code>optional bool is_valid = 1;</code>
     */
    public boolean hasIsValid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool is_valid = 1;</code>
     */
    public boolean getIsValid() {
      return isValid_;
    }

    // optional int64 expand_bit = 2;
    public static final int EXPAND_BIT_FIELD_NUMBER = 2;
    private long expandBit_;
    /**
     * <code>optional int64 expand_bit = 2;</code>
     */
    public boolean hasExpandBit() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 expand_bit = 2;</code>
     */
    public long getExpandBit() {
      return expandBit_;
    }

    // optional string title = 3;
    public static final int TITLE_FIELD_NUMBER = 3;
    private java.lang.Object title_;
    /**
     * <code>optional string title = 3;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string title = 3;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 channel_id = 4;
    public static final int CHANNEL_ID_FIELD_NUMBER = 4;
    private int channelId_;
    /**
     * <code>optional int32 channel_id = 4;</code>
     */
    public boolean hasChannelId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 channel_id = 4;</code>
     */
    public int getChannelId() {
      return channelId_;
    }

    // repeated string virtual_channel = 12;
    public static final int VIRTUAL_CHANNEL_FIELD_NUMBER = 12;
    private com.google.protobuf.LazyStringList virtualChannel_;
    /**
     * <code>repeated string virtual_channel = 12;</code>
     */
    public java.util.List<java.lang.String>
        getVirtualChannelList() {
      return virtualChannel_;
    }
    /**
     * <code>repeated string virtual_channel = 12;</code>
     */
    public int getVirtualChannelCount() {
      return virtualChannel_.size();
    }
    /**
     * <code>repeated string virtual_channel = 12;</code>
     */
    public java.lang.String getVirtualChannel(int index) {
      return virtualChannel_.get(index);
    }
    /**
     * <code>repeated string virtual_channel = 12;</code>
     */
    public com.google.protobuf.ByteString
        getVirtualChannelBytes(int index) {
      return virtualChannel_.getByteString(index);
    }

    // optional double sns_score = 13;
    public static final int SNS_SCORE_FIELD_NUMBER = 13;
    private double snsScore_;
    /**
     * <code>optional double sns_score = 13;</code>
     */
    public boolean hasSnsScore() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double sns_score = 13;</code>
     */
    public double getSnsScore() {
      return snsScore_;
    }

    // repeated int64 child_clip_id = 111;
    public static final int CHILD_CLIP_ID_FIELD_NUMBER = 111;
    private java.util.List<java.lang.Long> childClipId_;
    /**
     * <code>repeated int64 child_clip_id = 111;</code>
     */
    public java.util.List<java.lang.Long>
        getChildClipIdList() {
      return childClipId_;
    }
    /**
     * <code>repeated int64 child_clip_id = 111;</code>
     */
    public int getChildClipIdCount() {
      return childClipId_.size();
    }
    /**
     * <code>repeated int64 child_clip_id = 111;</code>
     */
    public long getChildClipId(int index) {
      return childClipId_.get(index);
    }

    private void initFields() {
      isValid_ = false;
      expandBit_ = 0L;
      title_ = "";
      channelId_ = 0;
      virtualChannel_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      snsScore_ = 0D;
      childClipId_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isValid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, expandBit_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, channelId_);
      }
      for (int i = 0; i < virtualChannel_.size(); i++) {
        output.writeBytes(12, virtualChannel_.getByteString(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(13, snsScore_);
      }
      for (int i = 0; i < childClipId_.size(); i++) {
        output.writeInt64(111, childClipId_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isValid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, expandBit_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, channelId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < virtualChannel_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(virtualChannel_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getVirtualChannelList().size();
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(13, snsScore_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < childClipId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(childClipId_.get(i));
        }
        size += dataSize;
        size += 2 * getChildClipIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PB.Info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PB.Info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PB.Info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PB.Info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PB.Info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PB.Info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PB.Info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PB.Info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PB.Info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PB.Info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PB.Info prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Info}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PB.InfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PB.internal_static_Info_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PB.internal_static_Info_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PB.Info.class, PB.Info.Builder.class);
      }

      // Construct using PB.Info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isValid_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        expandBit_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        channelId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        virtualChannel_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        snsScore_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        childClipId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PB.internal_static_Info_descriptor;
      }

      public PB.Info getDefaultInstanceForType() {
        return PB.Info.getDefaultInstance();
      }

      public PB.Info build() {
        PB.Info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PB.Info buildPartial() {
        PB.Info result = new PB.Info(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isValid_ = isValid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.expandBit_ = expandBit_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.channelId_ = channelId_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          virtualChannel_ = new com.google.protobuf.UnmodifiableLazyStringList(
              virtualChannel_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.virtualChannel_ = virtualChannel_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.snsScore_ = snsScore_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          childClipId_ = java.util.Collections.unmodifiableList(childClipId_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.childClipId_ = childClipId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PB.Info) {
          return mergeFrom((PB.Info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PB.Info other) {
        if (other == PB.Info.getDefaultInstance()) return this;
        if (other.hasIsValid()) {
          setIsValid(other.getIsValid());
        }
        if (other.hasExpandBit()) {
          setExpandBit(other.getExpandBit());
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000004;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasChannelId()) {
          setChannelId(other.getChannelId());
        }
        if (!other.virtualChannel_.isEmpty()) {
          if (virtualChannel_.isEmpty()) {
            virtualChannel_ = other.virtualChannel_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureVirtualChannelIsMutable();
            virtualChannel_.addAll(other.virtualChannel_);
          }
          onChanged();
        }
        if (other.hasSnsScore()) {
          setSnsScore(other.getSnsScore());
        }
        if (!other.childClipId_.isEmpty()) {
          if (childClipId_.isEmpty()) {
            childClipId_ = other.childClipId_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureChildClipIdIsMutable();
            childClipId_.addAll(other.childClipId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PB.Info parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PB.Info) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bool is_valid = 1;
      private boolean isValid_ ;
      /**
       * <code>optional bool is_valid = 1;</code>
       */
      public boolean hasIsValid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool is_valid = 1;</code>
       */
      public boolean getIsValid() {
        return isValid_;
      }
      /**
       * <code>optional bool is_valid = 1;</code>
       */
      public Builder setIsValid(boolean value) {
        bitField0_ |= 0x00000001;
        isValid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_valid = 1;</code>
       */
      public Builder clearIsValid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isValid_ = false;
        onChanged();
        return this;
      }

      // optional int64 expand_bit = 2;
      private long expandBit_ ;
      /**
       * <code>optional int64 expand_bit = 2;</code>
       */
      public boolean hasExpandBit() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 expand_bit = 2;</code>
       */
      public long getExpandBit() {
        return expandBit_;
      }
      /**
       * <code>optional int64 expand_bit = 2;</code>
       */
      public Builder setExpandBit(long value) {
        bitField0_ |= 0x00000002;
        expandBit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 expand_bit = 2;</code>
       */
      public Builder clearExpandBit() {
        bitField0_ = (bitField0_ & ~0x00000002);
        expandBit_ = 0L;
        onChanged();
        return this;
      }

      // optional string title = 3;
      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 3;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string title = 3;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 3;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 3;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000004);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 3;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        title_ = value;
        onChanged();
        return this;
      }

      // optional int32 channel_id = 4;
      private int channelId_ ;
      /**
       * <code>optional int32 channel_id = 4;</code>
       */
      public boolean hasChannelId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 channel_id = 4;</code>
       */
      public int getChannelId() {
        return channelId_;
      }
      /**
       * <code>optional int32 channel_id = 4;</code>
       */
      public Builder setChannelId(int value) {
        bitField0_ |= 0x00000008;
        channelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 channel_id = 4;</code>
       */
      public Builder clearChannelId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        channelId_ = 0;
        onChanged();
        return this;
      }

      // repeated string virtual_channel = 12;
      private com.google.protobuf.LazyStringList virtualChannel_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureVirtualChannelIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          virtualChannel_ = new com.google.protobuf.LazyStringArrayList(virtualChannel_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string virtual_channel = 12;</code>
       */
      public java.util.List<java.lang.String>
          getVirtualChannelList() {
        return java.util.Collections.unmodifiableList(virtualChannel_);
      }
      /**
       * <code>repeated string virtual_channel = 12;</code>
       */
      public int getVirtualChannelCount() {
        return virtualChannel_.size();
      }
      /**
       * <code>repeated string virtual_channel = 12;</code>
       */
      public java.lang.String getVirtualChannel(int index) {
        return virtualChannel_.get(index);
      }
      /**
       * <code>repeated string virtual_channel = 12;</code>
       */
      public com.google.protobuf.ByteString
          getVirtualChannelBytes(int index) {
        return virtualChannel_.getByteString(index);
      }
      /**
       * <code>repeated string virtual_channel = 12;</code>
       */
      public Builder setVirtualChannel(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVirtualChannelIsMutable();
        virtualChannel_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string virtual_channel = 12;</code>
       */
      public Builder addVirtualChannel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVirtualChannelIsMutable();
        virtualChannel_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string virtual_channel = 12;</code>
       */
      public Builder addAllVirtualChannel(
          java.lang.Iterable<java.lang.String> values) {
        ensureVirtualChannelIsMutable();
        super.addAll(values, virtualChannel_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string virtual_channel = 12;</code>
       */
      public Builder clearVirtualChannel() {
        virtualChannel_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string virtual_channel = 12;</code>
       */
      public Builder addVirtualChannelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVirtualChannelIsMutable();
        virtualChannel_.add(value);
        onChanged();
        return this;
      }

      // optional double sns_score = 13;
      private double snsScore_ ;
      /**
       * <code>optional double sns_score = 13;</code>
       */
      public boolean hasSnsScore() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double sns_score = 13;</code>
       */
      public double getSnsScore() {
        return snsScore_;
      }
      /**
       * <code>optional double sns_score = 13;</code>
       */
      public Builder setSnsScore(double value) {
        bitField0_ |= 0x00000020;
        snsScore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double sns_score = 13;</code>
       */
      public Builder clearSnsScore() {
        bitField0_ = (bitField0_ & ~0x00000020);
        snsScore_ = 0D;
        onChanged();
        return this;
      }

      // repeated int64 child_clip_id = 111;
      private java.util.List<java.lang.Long> childClipId_ = java.util.Collections.emptyList();
      private void ensureChildClipIdIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          childClipId_ = new java.util.ArrayList<java.lang.Long>(childClipId_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated int64 child_clip_id = 111;</code>
       */
      public java.util.List<java.lang.Long>
          getChildClipIdList() {
        return java.util.Collections.unmodifiableList(childClipId_);
      }
      /**
       * <code>repeated int64 child_clip_id = 111;</code>
       */
      public int getChildClipIdCount() {
        return childClipId_.size();
      }
      /**
       * <code>repeated int64 child_clip_id = 111;</code>
       */
      public long getChildClipId(int index) {
        return childClipId_.get(index);
      }
      /**
       * <code>repeated int64 child_clip_id = 111;</code>
       */
      public Builder setChildClipId(
          int index, long value) {
        ensureChildClipIdIsMutable();
        childClipId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 child_clip_id = 111;</code>
       */
      public Builder addChildClipId(long value) {
        ensureChildClipIdIsMutable();
        childClipId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 child_clip_id = 111;</code>
       */
      public Builder addAllChildClipId(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureChildClipIdIsMutable();
        super.addAll(values, childClipId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 child_clip_id = 111;</code>
       */
      public Builder clearChildClipId() {
        childClipId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Info)
    }

    static {
      defaultInstance = new Info(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Info)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Info_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Info_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025protobuf-define.proto\"\222\001\n\004Info\022\020\n\010is_v" +
      "alid\030\001 \001(\010\022\022\n\nexpand_bit\030\002 \001(\003\022\r\n\005title\030" +
      "\003 \001(\t\022\022\n\nchannel_id\030\004 \001(\005\022\027\n\017virtual_cha" +
      "nnel\030\014 \003(\t\022\021\n\tsns_score\030\r \001(\001\022\025\n\rchild_c" +
      "lip_id\030o \003(\003B\004B\002PB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Info_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Info_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Info_descriptor,
              new java.lang.String[] { "IsValid", "ExpandBit", "Title", "ChannelId", "VirtualChannel", "SnsScore", "ChildClipId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
